name: flutter_quill
description: A rich text editor built for the modern Android, iOS, web and
  desktop platforms. It is the WYSIWYG editor and a Quill component for Flutter.
version: 9.1.1
homepage: https://1o24bbs.com/c/bulletjournal/108/
repository: https://github.com/singerdmx/flutter-quill/
issue_tracker: https://github.com/singerdmx/flutter-quill/issues/
documentation: https://github.com/singerdmx/flutter-quill/

topics:
  - ui
  - widgets
  - widget
  - rich-text-editor
  - quill

screenshots:
  - description: "Screenshot 1"
    path: example/assets/images/screenshot_1.png
  - description: "Screenshot 2"
    path: example/assets/images/screenshot_2.png
  - description: "Screenshot 3"
    path: example/assets/images/screenshot_3.png
  - description: "Screenshot 4"
    path: example/assets/images/screenshot_4.png

platforms:
  ? android
  ? ios
  ? linux
  ? macos
  ? web
  ? windows

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.17.0
  dart_quill_delta: ^10.2.0
  device_info_plus: ^10.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_keyboard_visibility: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_quill_delta_from_html: ^1.4.1
  gal: ^2.3.0
  html: ^0.15.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  markdown: ^7.2.1
  meta: ^1.10.0
  photo_view: ^0.14.0
  quiver: ^3.2.1
  super_clipboard: ^0.8.5
  universal_html: ^2.2.4
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_quill_test: ^10.0.0
  flutter_test:
    sdk: flutter
  http: ^1.2.1

  path: any
  test: ^1.24.3
  yaml: ^3.1.2

  # For scripts only
  yaml_edit: ^2.2.1
flutter:
  uses-material-design: true
  generate: true
